---
# tasks file for mariadb
- name: Install mariadb for CentOS
  dnf: 
    name: mariadb
    state: latest
    update_cache: yes
  when: ansible_distribution == "CentOS"

- name: Install mariadb for Ubuntu
  apt:
    name: mariadb
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

